#! /bin/zsh

#multimonitor setup
iwatch -c "/home/victor/bin/monitor-switcher-triggered" -e modify ${HOME}/.monitor-switcher.log &

pkill polybar
# pgrep -x sxhkd > /dev/null || sxhkd &
pgrep sxhkd || sxhkd -c ~/.config/sxhkd/sxhkdrc &

MONITOR_COUNT=`xrandr | grep -c " connected"`

#Remove just a little bit of the blue lights
xrandr --output eDP-1 --gamma 1:1:0.8
xrandr --output HDMI-1 --gamma 1:1:0.8

#Default brightness
xrandr --output eDP-1 --brightness 1
xrandr --output HDMI-1 --brightness 1

if [[ $MONITOR_COUNT -eq 1 ]]; then
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7
else
    bspc monitor eDP-1 -d 1 2 3
    bspc monitor HDMI-1 -d 4 5 6 7
fi

bspc config border_width         0
bspc config window_gap           4

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a URxvt desktop='1' state tiled follow=on
bspc rule -a Emacs desktop='5' state=tiled follow=on
bspc rule -a Loading.. desktop='1' state=floating follow=off
bspc rule -a nubank desktop='1' state=floating follow=off
bspc rule -a Slack desktop='3' state=tiled
bspc rule -a Google-chrome desktop='4' state=tiled follow=on
bspc rule -a Org.gnome.Nautilus desktop='5' state=tiled follow=on
bspc rule -a Peek state=floating follow=on
bspc rule -a Yad state=floating
bspc rule -a gpclient state=floating desktop='1'
bspc rule -a Gnome-calculator state=floating desktop='1' follow=on

# Set cursor speed and delay
xset r rate 220 50

# Set background
feh --bg-scale ~/.dotfiles/background.png

# Set keymap to us-intl
setxkbmap -layout us -variant intl

# Set natural scrolling to 1
xinput set-prop 15 319 1
xinput set-prop 12 319 1
xinput set-prop 13 319 1

polybar &

dunst &

pkill slack

slack &

flameshot &

playerctl &

eval $(ssh-agent)
