#!/bin/sh

#autostart
pgrep -x sxhkd > /dev/null || sxhkd &
pkill picom
picom &

#monitor
bspc monitor -d 1 2 3 4

#window information
bspc config border_width 0
bspc config pointer_follow_monitor true
bspc config focus_follows_pointer true

#rules
#TODO