#!/usr/bin/env bash

date >> /tmp/bspwm.debug
# BSPWM Configuration

# Autostart
xrandr --output DP-1 --mode 1920x1080 --rate 144.00 --right-of HDMI-1
xrandr --output HDMI-1 --mode 1920x1080 --rate 75.00

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitor config
bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10

bspc wm --reorder-monitors DP-1 HDMI-1

bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

# Rules
bspc rule -a Emacs desktop='^2' state=fullscreen follow=on
bspc rule -a Google-chrome desktop='^3' state=tiled follow=on
